Repository christfellowshipchurch/web-app-v2, pull requests merged in 2021-12, with the labels that each got.

#402 Feature - Rich Text Editor
  .storybook/main.js
  components/GroupEmailComposer/GroupEmailComposer.js
  components/GroupEmailComposer/GroupEmailComposer.styles.js
  components/Modals/WelcomeModal/WelcomeModal.js
  package.json
  pages/_app.js
  ui-kit/RichTextEditor/RichTextEditor.js
  ui-kit/RichTextEditor/RichTextEditor.stories.js
  ui-kit/RichTextEditor/RichTextEditor.styles.js
  ui-kit/RichTextEditor/index.js
  ui-kit/_config/colors.js
  ui-kit/index.js
  yarn.lock
Labels: feature, Groups Platform

#404 Feature email composer confirmation
  components/GroupEmailComposer/GroupEmailComposer.js
  components/Modals/GroupEmailComposerConfirmationModal/GroupEmailComposerConfirmationModal.js
  components/Modals/GroupEmailComposerConfirmationModal/index.js
  components/Modals/index.js
  config/modals.js
Labels: feature, Groups Platform

#406 Update LocationSingle.js
  components/LocationSingle/LocationSingle.js
Labels: bug

#405 Select email recepients
  components/GroupEmailComposer/AvatarRow.js
  components/GroupEmailComposer/GroupEmailComposer.js
  components/GroupManage/GroupManageMembers.js
  components/Modals/GroupEmailComposerConfirmationModal/GroupEmailComposerConfirmationModal.js
  components/Modals/GroupEmailComposerConfirmationModal/index.js
  components/Modals/GroupEmailRecipientModal/AvatarRow.js
  components/Modals/GroupEmailRecipientModal/GroupEmailRecipientModal.js
  components/Modals/GroupEmailRecipientModal/index.js
  components/Modals/GroupMemberDetailsModal/GroupMemberDetailsModal.js
  components/Modals/index.js
  config/modals.js
  hooks/index.js
  hooks/useGroupEmailRecipients.js
  lib/apolloClient/initCache.js
  package.json
  pages/group/[title]/email.js
  ui-kit/_config/icons.js
  yarn.lock
Labels: feature, Groups Platform

#408 Release - Groups Home Page Update
  components/CommunityLeaderActions/CommunityLeaderActions.js
  components/CommunitySingle/CommunitySingle.js
  components/CommunitySingle/VideoPlayButton.js
  components/SearchField/SearchField.js
  components/SearchField/SearchField.styles.js
  pages/groups/Community.styles.js
  pages/groups/index.js
  pages/groups/search/Sidebar.js
  pages/groups/search/index.js
  public/groups-cover-image.jpg
  public/groups-cover-image.png
Labels: release, Groups Platform
