Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-06, with the labels that each got.

#548 Adjusting My Prayers title on the Connect page
  components/HorizontalCardListFeature/HorizontalCardListFeature.js
  ui-kit/GroupCard/GroupCard.styles.js
Labels: bug

#545 Changed FAQ Scrolling
  components/FAQ/FAQ.js
  components/LocationSingle/LocationSingle.js
Labels: enhancement, Location Pages

#544 Added Redirect for Riviera Location Page
  next.config.js
  public/_redirects
Labels: 🛑 DO NOT MERGE 🛑, Location Pages

#552 Items are now aligned to the left
  components/GroupSingle/GroupResources.js
Labels: bug

#551 Fixed the Other Check Box on Connect Card
  components/Modals/ConnectCardModal/ConnectCardForm.js
  components/Modals/ConnectCardModal/StyledForm.js
Labels: bug

#555 Removed "clickable" functionality for non-clickable redirect cards
  components/HeroListFeature/HeroListFeature.js
  components/HorizontalCardListFeature/HorizontalCardListFeature.js
Labels: bug

#556 Fixed Group End Date Bug
  components/GroupSingle/GroupSingle.js
Labels: Bug 🐛, Ready for Review ✅

#558 Fix Card Bug on External Home
  components/ExternalHome/StartHere.js
Labels: Bug 🐛, Ready for Review ✅

#559 Discover back button
  components/DiscoverFilterSection/DiscoverFilterSection.js
  components/DiscoverFiltersMap/DiscoverFiltersMap.js
  pages/discover/[title].js
  pages/discover/index.js
Labels: Enhancement ✨, Ready for Review ✅

#562 Updated page to reflect last changes
  components/FAQ/faqData.js
  components/LocationSingle/CampusInfo.js
  config/metadata.js
  config/mobile-nav-links.js
Labels: Location Pages 📍, Ready for Review ✅

#565 Map Link for Location Pages
  components/LocationSingle/CampusInfo.js
  components/LocationSingle/locationData.js
  hooks/useCampus.js
Labels: Location Pages 📍, Ready for Review ✅
