Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-05, with the labels that each got.

#529 Set Reminder Section for Location Pages
  components/InfoCardList/InfoCardList.js
  components/InfoCardList/index.js
  components/LocationSingle/LocationSingle.js
  components/LocationSingle/locationData.js
  components/index.js
  ui-kit/_config/icons.js
Labels: Location Pages

#534 Removed overlay for all default cards when there is no title
  components/VerticalCardListFeature/VerticalCardListFeature.js
  ui-kit/DefaultCard/DefaultCard.js
Labels: enhancement

#538 Fixed the FAQ Scroll
  components/FAQ/FAQ.js
  components/LocationSingle/LocationSingle.js
Labels: bug
