Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-12, with the labels that each got.

#636 Added margin bottom for share button
  components/EventSingle/EventSingle.js
Labels: Bug 🐛, Ready for Review ✅

#633 Saving search input in discover
  components/ContentSingle/ContentSingle.js
  components/DiscoverFilterSection/DiscoverFilterSection.js
  pages/discover/[title].js
  pages/discover/index.js
Labels: Bug 🐛, Ready for Review ✅

#638 Articles Bug Fix
  components/ContentSingle/ContentSingle.js
Labels: Bug 🐛, Ready for Review ✅

#637 Christmas Banner
  components/LocationSingle/CampusInfo/index.js
  components/LocationSingle/LocationSingle.styles.js
  public/location-pages/christmas-banner.jpeg
Labels: Ready for Review ✅

#640 Fixed Card size on /groups and Location Button
  components/CommunityList/CommunityListCard.js
  components/LocationSingle/CampusInfo/PastorCard.js
Labels: Bug 🐛

#641 Discover Bug Fix
  pages/discover/[title].js
Labels: Bug 🐛, Ready for Review ✅

#642 Adding Note to Banner
  components/LocationSingle/CampusInfo/index.js
  components/LocationSingle/LocationSingle.styles.js
Labels: Location Pages 📍, Ready for Review ✅
