Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-07, with the labels that each got.

#564 Content Blocks - Adding a Video to the Layout "Content to the Right" or "Content to the Left"
  components/Video/Video.js
  ui-kit/ContentBlock/ContentBlock.js
Labels: Ready for Review ✅

#566 Wistia Videos Not Showing on Articles
  components/ContentSingle/ContentSingle.js
  components/ContentSingle/ContentVideo.js
Labels: Bug 🐛, Ready for Review ✅

#569 Updated subtitle for 'My Groups'
  components/HorizontalCardListFeature/HorizontalCardListFeature.js
Labels: Ready for Review ✅

#570 Added Person Guid to Analytics Tracking
  hooks/useCurrentUser.js
  providers/AnalyticsProvider.js
Labels: External Marketing 📊, Ready for Review ✅

#579 Add to Calendar for Confirmation Modal v2
  components/LocationSingle/CampusInfo.js
  components/LocationSingle/LocationSingle.js
  components/Modals/AddToCalendarModal/AddToCalendarModal.js
  components/Modals/ConnectCardModal/Confirmation.js
  components/Modals/SetReminderModal/SetAReminder.js
  components/Modals/SetReminderModal/SetAReminderForm.js
  utils/icsLinkEvents.js
  utils/index.js
Labels: Ready for Review ✅

#581 Encrypted Links for Background Videos
  components/LocationSingle/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#582 Made modals scrollable
  components/Modals/ConnectCardModal/utils.js
  ui-kit/Modal/Modal.styles.js
Labels: Ready for Review ✅

#587 Group Chat now shows on mobile
  components/GroupSingle/GroupChat.js
Labels: Ready for Review ✅
