Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-10, with the labels that each got.

#500 Share sheet button
  components/ContentLayout/ContentLayout.js
  components/ContentSingle/ContentSingle.js
  components/Share/Share.js
  components/Share/shareUtils.js
  ui-kit/HtmlRenderer/tags/Img/DownloadButton.js
  ui-kit/_config/icons.js
Labels: Bug 🐛, Ready for Review ✅

#613 Groups resources tags
  components/ActionListFeature/ActionListFeature.js
  components/GroupManage/AddResourceContent.js
  components/GroupManage/GroupManage.js
  components/GroupManage/GroupManageMembers.js
  components/GroupManage/GroupManageResources.js
  hooks/index.js
  hooks/useGetTaggedItems.js
  hooks/useGetTags.js
  pages/so-good-sisterhood/season/[title].js
  providers/GroupResourceOptionsProvider.js
Labels: Groups Platform 🙋‍♂️, Ready for Review ✅

#620 Jupiter Changes
  components/LocationSingle/LocationSingle.js
  components/LocationSingle/locationData.js
Labels: Ready for Review ✅

#621 Group resources ordering
  components/GroupManage/ResourcesList.js
  components/GroupSingle/GroupResources.js
Labels: Ready for Review ✅

#623 Removed Spanish translations
  components/LocationSingle/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#622 Added logic to change title and copy for CF Everywhere
  components/LocationSingle/locationData.js
Labels: Bug 🐛, Ready for Review ✅

#628 Content Search - Added Filter for Bad Duplicates
  hooks/useSearchContentItems.js
Labels: Bug 🐛, Ready for Review ✅
