Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-09, with the labels that each got.

#593 External Home 2.0
  components/CollectionPreview/CollectionPreview.js
  components/ExternalHome/LifeIsCrazy.js
  components/ExternalHome/LifeToTheFullest.js
  components/ExternalHome/StartHere.js
  components/ExternalHome/ThriveInEveryArea.js
  components/Footer/Footer.js
  components/Header/TransparentHeader.js
  components/HeroLanding/HeroButtons.js
  components/HeroLanding/HeroLanding.js
  components/HeroLanding/HeroLanding.styles.js
  components/Nav/Nav.js
  hooks/index.js
  hooks/useExternalHomeActions.js
  lib/externalHomeData.js
  package.json
  pages/external-home.js
  pages/groups/search/index.js
  providers/ContentItemProvider.js
  public/background-dots-orange.png
  public/external-landing/ask-a-question.png
  public/external-landing/corner-desktop.png
  public/external-landing/corner-mobile.png
  public/external-landing/dots-desktop.png
  public/external-landing/dots-mobile.png
  public/external-landing/find-a-location.jpg
  public/external-landing/find-a-location.png
  public/external-landing/kids.jpeg
  public/external-landing/students.jpeg
  public/external-landing/thrive-in-every-area.png
  public/external-landing/thrive-line-dots15x.png
  public/external-landing/wedge-desktop.png
  public/external-landing/wedge-mobile.png
  public/external-landing/young-adults.jpeg
  public/start-here-corners.png
  public/start-here-dots.png
  public/start-here-wedge.png
  ui-kit/Button/Button.js
  ui-kit/Card/Card.styles.js
  ui-kit/DefaultCard/DefaultCard.js
  ui-kit/HorizontalHighlightCard/HorizontalHighlightCard.js
  ui-kit/_config/icons.js
  yarn.lock
Labels: External Marketing 📊, In Progress 👨‍💻

#605 Changed PSL Spanish translation time
  components/LocationSingle/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#603 Group Search Bug 2.0
  pages/groups/search/index.js
Labels: Bug 🐛, Ready for Review ✅

#602 Fixed Wistia in Events
  components/EventSingle/EventSingle.js
  hooks/useContentItem.js
Labels: Enhancement ✨, Ready for Review ✅

#606 Color changes with transparent header
  components/Nav/Nav.js
  components/Nav/SignIn.js
  components/UserAvatar/UserAvatar.js
  ui-kit/Avatar/Avatar.styles.js
Labels: Bug 🐛, Ready for Review ✅

#607 Apollos - Rock Person ID Authentication
  components/Header/DefaultHeader.js
  hooks/index.js
  hooks/useAuthenticateRockPersonId.js
  hooks/useGroupContentId.js
  pages/connect/index.js
  pages/home.js
  providers/AuthProvider.js
  providers/FeatureFeedProvider.js
Labels: Enhancement ✨, Ready for Review ✅

#612 ASL Changed from Gardens to Trinity
  components/LocationSingle/locationData.js
Labels: Ready for Review ✅

#609 Changed the formatting of 20's + 30's
  lib/externalHomeData.js
Labels: Bug 🐛, Ready for Review ✅

#611 Made the border of the sign-in icon color dynamic
  components/Nav/SignIn.js
Labels: Bug 🐛, Ready for Review ✅

#608 What to Expect Section
  components/LocationBlockFeature/LocationBlockFeature.js
  components/LocationBlockFeature/LocationBlockFeature.styles.js
  components/LocationSingle/LocationSingle.js
  components/LocationSingle/locationData.js
  pages/about/index.js
  ui-kit/ContentBlock/ContentBlock.js
  ui-kit/ContentBlock/ContentBlock.styles.js
Labels: Enhancement ✨, Location Pages 📍, Ready for Review ✅

#615 Modals Bug
  components/Header/Header.styles.js
  components/Header/TransparentHeader.js
  components/LocationSingle/OldLocationSingle/OldLocationSingle.js
  ui-kit/Menu/Menu.styles.js
  ui-kit/Modal/Modal.styles.js
Labels: Bug 🐛, Ready for Review ✅

#616 Events Header Video Fix
  components/ContentLayout/ContentLayout.js
  components/ContentSingle/ContentSingle.js
  components/EventSingle/EventSingle.js
  components/Video/Video.js
  components/WistiaPlayer/WistiaPlayer.js
Labels: Ready for Review ✅

#617 Last minute sisterhood redirect for Pam
  next.config.js
  public/_redirects
Labels: Ready for Review ✅

#618 Fixed Event and Content Layout Image/Video Display
  components/ContentLayout/ContentLayout.js
  components/EventSingle/EventSingle.js
Labels: Bug 🐛, Ready for Review ✅

#604 Updated icons
  components/AddToCalendar/AddToCalendar.js
  components/DisplayAllIcons/DisplayAllIcons.js
  components/DisplayAllIcons/index.js
  components/LocationSingle/locationData.js
  components/Modals/ConnectCardModal/StyledForm.js
  components/Modals/SetReminderModal/StyledForm.js
  components/index.js
  config/navigation.js
  lib/externalHomeData.js
  pages/icons-rendering.js
  ui-kit/GroupCard/GroupCard.js
  ui-kit/_config/icons.js
Labels: Ready for Review ✅, Internal Use 🔒
