Repository christfellowshipchurch/web-app-v2, pull requests merged in 2023-08, with the labels that each got.

#594 Promotional Video for Events
  components/EventSingle/EventSingle.js
Labels: Ready for Review ✅

#591 Added SEU CTA to Nav Menu
  config/mobile-nav-links.js
  config/new-nav-links.js
Labels: Ready for Review ✅

#595 Added Wistia Id to Content Block Feature
  components/ContentBlockFeature/ContentBlockFeature.js
  fragments/features.js
  ui-kit/ContentBlock/ContentBlock.js
Labels: Enhancement ✨, Ready for Review ✅

#596 Fixed scrolling issue and cleaned up the code
  pages/login/reset-password/index.js
Labels: Bug 🐛, Ready for Review ✅

#597 HomeFeed ActionBar
  components/ActionBarFeature/ActionBarFeature.js
  lib/actionBarData.js
  pages/home.js
Labels: Enhancement ✨, Ready for Review ✅

#598 Added Videos and Logic to Set a Reminder Section on Location Pages
  components/LocationSingle/LocationSingle.js
  components/LocationSingle/locationData.js
Labels: Enhancement ✨, Location Pages 📍, Ready for Review ✅

#599 Fixed Sizing for Cards to all be the same
  components/CommunitySingle/CommunitySingle.js
  ui-kit/GroupCard/GroupCard.js
  ui-kit/GroupCard/GroupCard.styles.js
Labels: Bug 🐛, Ready for Review ✅

#600 Updated light and dark logos
  public/logo-dark.png
  public/logo.png
Labels: Feature 🖥️, Ready for Review ✅
