Repository christfellowshipchurch/web-app-v2, pull requests merged in 2024-04, with the labels that each got.

#687 Easter 2024 Redirect
  next.config.js
  public/_redirects
Labels: 🛑 DO NOT MERGE 🛑, Ready for Review ✅

#689 Added a Set a Reminder Video to CFE Gardems
  lib/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#690 Updated 404 Page Ministries Link
  components/NotFound/NotFound.js
Labels: Ready for Review ✅

#692 Removed Trinity SetAReminder Video
  lib/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#691 CF 40th Anniversary Logo Animation
  components/Logo/Logo.js
  components/LottieViewer/LottieViewer.js
  components/LottieViewer/index.js
  components/index.js
  package.json
  public/cf40-logo.json
  yarn.lock
Labels: 🛑 DO NOT MERGE 🛑, Ready for Review ✅
