Repository christfellowshipchurch/web-app-v2, pull requests merged in 2024-08, with the labels that each got.

#705 Added One Life Page
  pages/_document.js
  pages/one-life/index.js
Labels: External Marketing 📊

#707 Young Adults Copy Fix
  lib/externalHomeData.js
Labels: External Marketing 📊, Ready for Review ✅

#706 Google Tag Manager Installation
  components/AppHead/AppHead.js
  components/InfoCardList/InfoCardList.js
  components/LocationSingle/LocationHeader.js
  components/LocationSingle/LocationSingle.js
  components/Modals/SetReminderModal/StyledForm.js
  lib/locationData.js
  pages/_app.js
Labels: Enhancement ✨, Feature 🖥️, Ready for Review ✅

#710 Set a Reminder for Spanish
  components/Modals/ConnectCardModal/Confirmation.js
  components/Modals/SetReminderModal/StyledForm.js
  providers/AnalyticsProvider.js
Labels: Ready for Review ✅

#711 Our History Update
  lib/aboutData.js
  pages/about/index.js
Labels: Ready for Review ✅

#713 CFE Royal Palm Beach Set a Reminder Update
  lib/locationData.js
  pages/articles/[title].js
  ui-kit/HtmlRenderer/HtmlRenderer.styles.js
Labels: Ready for Review ✅
