Repository christfellowshipchurch/web-app-v2, pull requests merged in 2024-05, with the labels that each got.

#694 Added Trinity setReminder video
  lib/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#699 Added Wistia Player and new H4H video
  components/HeartForHouseComponents/StoryCarousel/StoryCarousel.components.js
  components/HeartForHouseComponents/StoryCarousel/StoryCarousel.data.js
Labels: External Marketing 📊, Ready for Review ✅

#700 Final H4H Video
  components/HeartForHouseComponents/StoryCarousel/StoryCarousel.data.js
Labels: Ready for Review ✅
