Repository christfellowshipchurch/web-app-v2, pull requests merged in 2024-02, with the labels that each got.

#664 Wistia Videos not Working on Content Single
  components/ContentSingle/ContentSingle.js
  components/ContentSingle/ContentVideo.js
Labels: Bug 🐛, Ready for Review ✅

#665 Get there first
  components/CardGridFeature/CardGridFeature.js
  components/CardGridFeature/CardGridFeature.styles.js
  components/CollectionPreview/CollectionPreview.js
  components/CustomLink/CustomLink.js
  components/GetThereFirstComponents/getThereFirstComponents.js
  components/GetThereFirstComponents/getThereFirstComponents.styles.js
  components/GetThereFirstComponents/getThereFirstData.js
  components/GetThereFirstComponents/index.js
  components/VideoHeader/VideoHeader.js
  pages/get-there-first/index.js
  pages/home.js
  pages/icons-rendering.js
  public/get-there-first/CFSEU.jpg
  public/get-there-first/KidsU.jpg
  public/get-there-first/Students.jpg
  public/get-there-first/YA.jpg
  public/get-there-first/background.jpg
  public/get-there-first/banner.jpg
  public/get-there-first/logo.png
  public/groups-cover-image.jpeg
  public/groups-cover-image.png
  ui-kit/CardGrid/CardGrid.styles.js
  ui-kit/ContentBlock/ContentBlock.js
  ui-kit/HorizontalHighlightCard/HorizontalHighlightCard.js
  ui-kit/HtmlRenderer/HtmlRenderer.js
Labels: Ready for Review ✅

#667 Hubspot Tracking
  components/AppHead/AppHead.js
Labels: Enhancement ✨, Ready for Review ✅

#672 Patched External Web Cards Bug
  components/CardGridFeature/CardGridFeature.js
Labels: Bug 🐛, External Marketing 📊
