Repository christfellowshipchurch/web-app-v2, pull requests merged in 2024-03, with the labels that each got.

#677 Easter Metadata Update and Fixes
  components/CardGridFeature/CardGridFeature.js
  components/EasterLocationSearch/EasterLocationHeader.js
  components/EasterLocationSearch/EasterLocationSearch.js
  components/FAQ/FAQ.js
  components/Modals/EasterLocationsModal/additionalComponents.js
  lib/easterServiceData.js
  pages/easter-2024-espanol/index.js
  pages/easter-2024/index.js
  public/easter/easter-metadata-espanol.jpg
  public/easter/easter-metadata.jpg
Labels: External Marketing 📊, Ready for Review ✅

#676 404 Update
  components/HeroLanding/HeroButtons.js
  components/NotFound/NotFound.js
Labels: Enhancement ✨, Ready for Review ✅

#675 External Web Updates
  components/ExternalHome/ThriveInEveryArea.js
  components/Footer/Footer.js
  components/LocationSingle/LocationSingle.js
  components/MobileNavScreen/MainMenu.js
  components/Modals/NavMenuModal/NavMenu.js
  config/metadata.js
  pages/external-home.js
Labels: External Marketing 📊, Ready for Review ✅

#670 Nav Menu Updates
  components/Modals/NavMenuModal/NavMenu.js
  config/mobile-nav-links.js
  config/new-nav-links.js
Labels: Ready for Review ✅

#668 Cards Width Fix
  components/DiscoverFilterSection/DiscoverFilterSection.js
  components/DiscoverItemsList/DiscoverItemsList.js
  pages/discover/[title].js
  pages/so-good-sisterhood/season/[title].js
  ui-kit/Card/Card.styles.js
  ui-kit/DefaultCard/DefaultCard.js
Labels: Bug 🐛, Ready for Review ✅

#678 Easter Modal Fixes
  components/Modals/EasterLocationsModal/EasterLocationsModal.js
  components/Modals/EasterLocationsModal/EasterLocationsModal.styles.js
  components/Modals/EasterLocationsModal/additionalComponents.js
Labels: Bug 🐛, Ready for Review ✅

#669 Horizontal Card List Update for Mobile View
  components/DiscoverFilterSection/DiscoverFilterSection.js
  components/DiscoverItemsList/DiscoverItemsList.js
  components/EasterLocationSearch/EasterLocationSearch.styles.js
  components/HorizontalCardListFeature/HorizontalCardListFeature.js
  components/NotFound/NotFound.js
  components/PageSingle/PageSingle.js
  pages/[title].js
  pages/discover/[title].js
  pages/so-good-sisterhood/season/[title].js
  ui-kit/HorizontalHighlightCard/HorizontalHighlightCard.js
  ui-kit/HorizontalScroll/HorizontalScroll.js
  ui-kit/HorizontalScroll/index.js
  ui-kit/index.js
Labels: Enhancement ✨, Ready for Review ✅

#679 Easter Banner
  components/LocationSingle/CampusInfo/CampusInfo.js
  components/LocationSingle/LocationSingle.js
  components/LocationSingle/LocationSingle.styles.js
  public/location-pages/easter-banner.png
Labels: Location Pages 📍, Ready for Review ✅

#682 Metadata Update for Location Pages
  lib/locationData.js
Labels: Location Pages 📍, Ready for Review ✅

#684 Easter Page Name Change
  components/EasterLocationSearch/EasterLocationHeader.js
  components/FAQ/faqData.js
  components/LocationSingle/CampusInfo/CampusInfo.js
  components/Modals/EasterLocationsModal/additionalComponents.js
  pages/easter-espanol/index.js
  pages/easter/index.js
Labels: Ready for Review ✅

#686 Easter 2024 Redirect Fix
  next.config.js
  public/_redirects
Labels: Bug 🐛, Ready for Review ✅
